server:
  port: 1122
  tomcat:
    threads:
      max: 10

spring:
  application:
    name: ticket-service

# Resilience4j
resilience4j.circuitbreaker:
  instances:
    getTickets:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
#      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

resilience4j.ratelimiter:
  instances:
    getTickets:
      limitForPeriod: 5
      limitRefreshPeriod: 10s
      timeoutDuration: 0
      registerHealthIndicator: true
      eventConsumerBufferSize: 100

# Actuator
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
